services:
  backend:
    build:
        context: .
        dockerfile: build/Dockerfile
    container_name: "backend_python"
    ports:
      - "8888:8080"
    env_file:
      - .env
    
    volumes:
      - .:/app

