services:
  backend:
    build:
        context: .
        dockerfile: build/Dockerfile
    container_name: "backend_python"
    ports:
      - "8888:8080"
    volumes:
      - .:/app
    depends_on:
      ollama-model:
        condition: service_healthy

  ollama-model:
    image: ollama/ollama
    container_name: ollama-model
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 8s


volumes:
  models: 
    driver: local