services:
  backend:
    build:
        context: .
        dockerfile: build/Dockerfile
    container_name: "backend_python"
    ports:
      - "8888:8080"
    volumes:
      - .:/app
  
  ollama-model:
    image: ollama/ollama
    container_name: ollama-model
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models

volumes:
  models: 
    driver: local