services:
  ollama-model:
    image: ollama/ollama
    container_name: ollama-model
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models
    networks:
      - redes_pulentas

volumes:
  models: 
    driver: localzz

networks:
  redes_pulentas:
    external: true