services:
  ollama-model:
    image: ollama/ollama
    container_name: ollama-model
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./models:/models

volumes:
  models: 
    driver: localzz